(DEFINITIONS) @keyword
(BEGIN) @keyword
(END) @keyword
(EXPORTS) @keyword
(IMPORTS) @keyword
(CLASS) @keyword
(WITH) @keyword
(SUCCESSORS) @keyword
(DESCENDANTS) @keyword
(INSTRUCTIONS) @keyword
(AUTOMATIC) @keyword
(IMPLIED) @keyword
(EXPLICIT) @keyword
(IMPLICIT) @keyword
(ALL) @keyword
(TAGS) @keyword
(EXTENSIBILITY) @keyword
(TYPE_IDENTIFIER) @keyword
(ABSTRACT_SYNTAX) @keyword
(UNIQUE) @keyword
(FROM) @keyword
(SYNTAX) @keyword
(CONTAINING) @keyword
(NULL) @keyword
(TRUE) @keyword
(FALSE) @keyword
(OCTET) @keyword
(STRING) @keyword
(BIT) @keyword
(SEQUENCE) @keyword
(SET) @keyword
(OF) @keyword
(DEFAULT) @keyword
(OPTIONAL) @keyword
(PLUS_INFINITY) @keyword
(MINUS_INFINITY) @keyword
(NOT_A_NUMBER) @keyword
(CHOICE) @keyword
(COMPONENTS) @keyword
(INTEGER) @keyword
(ENUMERATED) @keyword
(REAL) @keyword
(BMPString) @keyword
(GeneralString) @keyword
(GraphicString) @keyword
(IA5String) @keyword
(ISO646String) @keyword
(NumericString) @keyword
(PrintableString) @keyword
(TeletexString) @keyword
(T61String) @keyword
(UniversalString) @keyword
(UTF8String) @keyword
(VideotexString) @keyword
(VisibleString) @keyword
(UNIVERSAL) @keyword
(APPLICATION) @keyword
(PRIVATE) @keyword
(CHARACTER) @keyword
(EMBEDDED) @keyword
(PDV) @keyword
(MIN) @keyword
(MAX) @keyword
(EXCEPT) @keyword
(INTERSECTION) @keyword
(INCLUDES) @keyword
(INSTANCE) @keyword
(OBJECT) @keyword
(IDENTIFIER) @keyword
(UNION) @keyword
(PRESENT) @keyword
(ABSENT) @keyword
(PATTERN) @keyword
(SETTINGS) @keyword
(ENCODED) @keyword
(BY) @keyword
(CONSTRAINED) @keyword
(SIZE) @keyword
(BOOLEAN) @keyword
(RELATIVE_OID) @keyword
(OID_IRI) @keyword
(RELATIVE_OID_IRI) @keyword
(EXTERNAL) @keyword
(TIME) @keyword
(DATE) @keyword
(DATE_TIME) @keyword
(DURATION) @keyword
(TIME_OF_DAY) @keyword
(COMPONENT) @keyword
(block_comment) @comment
(line_comment) @comment
(identifier) @variable
(modulereference) @variable
(number) @number
(realnumber) @number
(cstring) @string
(bstring) @string
(hstring) @string
(ObjectIdentifierType) @type
"::=" @operator
".." @operator